"""create category table

Revision ID: 9d98f00e6fd5
Revises: 4488506b0687
Create Date: 2025-05-28 08:38:15.099507

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9d98f00e6fd5'
down_revision = '4488506b0687'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('category')
    op.drop_table('transactions')
    op.drop_table('wallets')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wallets',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('wallets_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('nama_dompet', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('deskripsi', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('saldo_awal', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0.0'), autoincrement=False, nullable=True),
    sa.Column('saldo_saat_ini', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0.0'), autoincrement=False, nullable=True),
    sa.Column('tipe_dompet', postgresql.ENUM('cash', 'bank', 'credit_card', 'e_wallet', name='wallettype'), autoincrement=False, nullable=False),
    sa.Column('warna', sa.VARCHAR(length=7), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='wallets_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('transactions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tipe_transaksi', postgresql.ENUM('income', 'expense', name='transactiontype'), autoincrement=False, nullable=False),
    sa.Column('jumlah', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('deskripsi', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('wallet_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tanggal', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('catatan', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name=op.f('fk_category')),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], name=op.f('fk_wallet'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('transactions_pkey'))
    )
    op.create_table('category',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('transaction_type', postgresql.ENUM('Income', 'Expense', name='transaction_type'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('category_pkey'))
    )
    # ### end Alembic commands ###
