"""create transactions table

Revision ID: 4488506b0687
Revises: bacc0139e8d7
Create Date: 2025-05-28 05:41:50.797782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4488506b0687'
down_revision = 'bacc0139e8d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
